### ISSUE TITLE
Move RFCs from kubewarden-controller repo to RFC repository.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/rfc#1]

**Comment by ereslibre** [comment]
This is already done, right? Thanks for doing it :)

Should we get rid of https://github.com/kubewarden/kubewarden-controller/tree/main/rfc now?

**Comment by ereslibre** [comment]
Note: there is one RFC pending, but I can move it over here.

**Comment by jvanz** [comment]
> Should we get rid of https://github.com/kubewarden/kubewarden-controller/tree/main/rfc now?

Yes. I think so. 

> Note: there is one RFC pending, but I can move it over here.

Maybe we can wait to finish the RPF PR and then move it to this repository, and delete the old directory. Just to avoid two PRs discussing the topic.
