### ISSUE TITLE
RFC: have a unified version for the whole Kubewarden stack

### ISSUE THREAD

**Issue by flavio** [kubewarden/rfc#5]
We would like to have a way to easily identify the version of Kubewarden a user is installing/running. Right now each component of kubewarden has its own different version number.

## Acceptance criteria

* Create a RFC that proposes a way to version Kubewarden that simplifies life of users, supporters and marketing

**Comment by jvanz** [comment]
@ereslibre should we keep this in pending review? I saw you closing the PR, can we move this to TODO? Or are we keeping this on review to discuss the card in a call?

**Comment by ereslibre** [comment]
Yes, I have to open another proposal with semver at the top. As far as I understood from the last meeting regarding this, I was going to close the previous PR (https://github.com/kubewarden/kubewarden-controller/pull/182) so we were able to check the discussion and everything on it, and I was going to open another PR with a different approach: using semver at the toplevel as well. I haven't done so yet.

**Comment by ereslibre** [comment]
Moved it to TODO, thank you.
